" See :help map-which-keys

" Status bar
    set showcmd
    set laststatus=2

" Indent
    set tabstop=4
    set shiftwidth=4
    set softtabstop=4
    set expandtab
    set autoindent
    set smartindent
    filetype on
    autocmd FileType ruby,tex,html,javascript,css,json
        \ setlocal shiftwidth=2 tabstop=2 softtabstop=2

" Search
    set nohlsearch

" Line number
    set nu
    set relativenumber

" Max chars per line
    set colorcolumn=80
    set textwidth=80

" Misc
    set ttimeoutlen=100

" Throws the content after the cursor to the line below
    nnoremap <CR> i<Enter><esc>k$

" Commands
    command Nvimrc tabe ~/.config/nvim/init.vim
    command Mainsplit vertical resize 84

" Plugins (Requires vim-plug)
    call plug#begin('~/.config/nvim/bundle')
        Plug 'michaeljsmith/vim-indent-object'
        Plug 'tpope/vim-surround'
        Plug 'wellle/targets.vim'
        Plug 'donRaphaco/neotex', { 'for': 'tex' }
        Plug 'pangloss/vim-javascript', { 'for': 'javascript' }
        Plug 'mxw/vim-jsx', { 'for': 'javascript' }
        Plug 'rafaqz/ranger.vim'
        Plug 'morhetz/gruvbox'
    call plug#end()

" Latex config
augroup latexconf
    autocmd!
    autocmd FileType tex let g:tex_flavor = 'latex'
    autocmd FileType tex nnoremap <leader>le :NeoTexOn<CR>
    autocmd FileType tex nnoremap <leader>ld :NeoTexOff<CR>
    autocmd FileType tex nnoremap <F9>
        \ <esc>:!FILENAME=%; zathura ${FILENAME\%.*}.pdf &<CR><CR>
augroup end

" Ranger plugin
    map <F2> :RangerTab<CR>
    map <F3> :RangerVSplit<CR>
    map <F4> :RangerSplit<CR>

" Color
    colorscheme gruvbox
    set cursorline
    highlight ColorColumn ctermbg=darkgray
