plugins=(rsync fzf)
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"
HIST_STAMPS="dd.mm.yyyy"
source $ZSH/oh-my-zsh.sh

export FZF_BASE=/usr/bin

source ~/.scripts/include/cli_functions.sh

alias diskusage="du -chad 1"
alias keycodes="xmodmap -pke"
alias enpt="translate_english_to_portuguese"
alias pten="translate_portuguese_to_english"

if [ -d ~/.gem/ruby ]; then
    LASTEST_RUBY_GEM_BIN="$(ls ~/.gem/ruby | sort | tail -1)"
    add_to_path_if_exists ~/.gem/ruby/$LASTEST_RUBY_GEM_BIN/bin
fi

if [ -d /opt/android-sdk ]
then
    export ANDROID_HOME=/opt/android-sdk
    export PATH=$PATH:$ANDROID_HOME/emulator
    export PATH=$PATH:$ANDROID_HOME/tools
    export PATH=$PATH:$ANDROID_HOME/tools/bin
    export PATH=$PATH:$ANDROID_HOME/platform-tools
fi

add_to_path_if_exists ~/.yarn/bin
add_to_path_if_exists ~/.bin
add_to_path_if_exists ~/.scripts/cli-commands

export PATH
export VISUAL=nvim
export EDITOR="$VISUAL"
export TERMINAL=termite
export TERM=termite
