# ZSH SPECIFIC
plugins=(fzf myutils)
ZSH_THEME="robbyrussell"
HIST_STAMPS="dd.mm.yyyy"
export ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

export FZF_DEFAULT_COMMAND="fd --hidden --follow --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd --type d --hidden --follow --exclude .git"

# Aliases
alias find="fd"
alias keycodes="xmodmap -pke"
alias enpt="translate_english_to_portuguese"
alias pten="translate_portuguese_to_english"
alias c='cd "$(fd --type d --hidden --follow --exclude .git | fzf)"'
alias e='nvim "$(fd --type f --hidden --follow --exclude .git | fzf)"'

# Adding to PATH
function add_to_path() {
    [[ ! -d "$1" ]] && return
    [[ ":$PATH:" == *":$1:"* ]] && return
    PATH="$PATH:$1"
}

if [ -d /opt/android-sdk ]; then
    export ANDROID_HOME=/opt/android-sdk
    add_to_path "$ANDROID_HOME/emulator"
    add_to_path "$ANDROID_HOME/tools"
    add_to_path "$ANDROID_HOME/tools/bin"
    add_to_path "$ANDROID_HOME/platform-tools"
fi

add_to_path ~/.yarn/bin
add_to_path ~/.bin
add_to_path ~/.scripts/cli-commands

# Exports
export PATH
export VISUAL=nvim
export EDITOR="$VISUAL"
export TERMINAL=termite
export TERM=termite
