plugins=(fzf)
ZSH_THEME="robbyrussell"
HIST_STAMPS="dd.mm.yyyy"
ZSH="$HOME/.oh-my-zsh"
source "$ZSH/oh-my-zsh.sh"

export FZF_DEFAULT_COMMAND="fd --hidden --follow --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd --type d --hidden --follow --exclude .git"

function include() {
    [[ -f "$1" ]] && source "$1" || echo "Could not include: \"$1\""
}

BASE_DIR="$HOME/.include/shell"

include "$BASE_DIR/path_exports.sh"
include "$BASE_DIR/aliases.sh"
include "$BASE_DIR/functions.sh"

unset BASE_DIR
unset -f include
