#!/usr/bin/env bash

source "$HOME/.include/scripts/menu.sh"

TMP_FILE="/tmp/menu-vpn-provided-password"

list_availables_vpns() {
    nmcli -f name,type connection show \
        | awk '{if($NF == "vpn") print $0;}' \
        | sed 's/\s*\w*\s*$//'
}

ask_to_select_vpn() {
    menu_select_item "$(list_availables_vpns)"
}

connect_to_selected_vpn() {
    selected_vpn="$(ask_to_select_vpn)"

    if [ $? -ne 0 ]; then
        notify-send "VPN" "Could not connect to VPN \"$selected_vpn\"."
    else
        notify-send "VPN" "Connected to VPN."
    fi
}

ask_password() {
    menu_input "VPN Password: "
}

VPN_TO_CONNECT="$(connect_to_selected_vpn)"
VPN_PASSWORD="$(ask_password)"

echo -n "$VPN_PASSWORD" > "$TMP_FILE"
nmcli connection up "$selected_vpn" passwd-file "$TMP_FILE"
rm "$TMP_FILE"
