#!/usr/bin/env bash
# Avoid using jq to parse the JSON, it's "slow" (see older commit)

function get_event_name {
    echo "$1" | grep -Po '"change":".*?"' | cut -f 2 -d ':' |  tr -d '"'
}

function get_active_workspace_name {
    echo "$1" | grep -Po '"name":".*?"' | head -1 | cut -f 2 -d ':' | tr -d '"'
}

function add_active_workspace {
    workspace_name="$1"

    if [[ ! " ${ACTIVE_WORKSPACES[*]} " =~ " $workspace_name " ]]; then
        ACTIVE_WORKSPACES+=("$workspace_name")
        update_eww_active_workspaces
    fi
}

function remove_active_workspace {
    workspace_name="$1"
    ACTIVE_WORKSPACES=($(echo "${ACTIVE_WORKSPACES[@]}" | sed "s/$1//g"))
    update_eww_active_workspaces
}

function set_initial_values {
    ACTIVE_WORKSPACES=($(i3-msg -t get_workspaces | jq ".[].name" | tr '\n' ' ' | tr -d '"'))
    update_eww_active_workspaces

    #TODO: set eww "focusedWorkspace" initial value
}

function update_eww_active_workspaces {
    ewwActiveWorkspaces="$(echo "[${ACTIVE_WORKSPACES[@]}]" | sed 's/ /,/g')"
    eww update activeWorkspaces="$ewwActiveWorkspaces"
}

declare -a ACTIVE_WORKSPACES
set_initial_values

i3-msg -t subscribe -m '[ "workspace" ]' | while read event; do
    eventName="$(get_event_name "$event")"
    workspaceName="$(get_active_workspace_name "$event")"

    case "$eventName" in
        "focus")
            eww update focusedWorkspace=$workspaceName
            add_active_workspace "$workspaceName"
            ;;
        "init") 
            add_active_workspace "$workspaceName"
            ;; 
        "empty")
            remove_active_workspace "$workspaceName"
            ;;
    esac
done
