#!/usr/bin/env bash

if [[ ! "$1" =~ ^-?[0-9]+(\.[0-9]+)?$ ]]; then
    echo "Usage: $0 gain"
    echo
    echo "gain: Basically, the mouse x/y pointer speed."
    echo "      Must be a decimal number. Default is 1."
    echo
    echo "eg.: change-mouse-sensitivy 1.5"
    exit 1
fi

mouse_speed="$1"

mouse_id="$( \
    xinput list \
    | grep "Mouse.*pointer" \
    | head -1 \
    | cut -d= -f 2 \
    | cut -f 1 \
)"

xinput set-prop \
    "$mouse_id" \
    "Coordinate Transformation Matrix" \
     $mouse_speed 0.0 0.0 0.0 $mouse_speed 0.0 0 0 1
