#!/bin/bash

export YDOTOOL_SOCKET="/tmp/.ydotool_socket"

SERVICE_NAME=ydotoold
SERVICE_FILE=~/.myrice/assets/services/ydotoold.service

if ! command -v ydotool &> /dev/null; then
    echo "Dependency not found. Installing..."

    sudo dnf install -y ydotool || {
        echo "Could not install ydotool. Aborting.";
        exit 1;
    }
fi

if ! systemctl is-active --quiet $SERVICE_NAME; then
    echo "ydotoold service is not active. Activating..."

    chmod 0644 "$SERVICE_FILE"
    sudo cp "$SERVICE_FILE" /etc/systemd/system

    sudo systemctl daemon-reload
    sudo systemctl enable $SERVICE_NAME
    sudo systemctl start $SERVICE_NAME
fi

X_1="$1"
Y_1="$2"

X_2="$3"
Y_2="$4"

while true; do
    sleep 2
    ydotool mousemove -- "$X_1" "$Y_1"
    sleep 2
    ydotool mousemove -- "$X_2" "$Y_2"
done
