#!/usr/bin/env bash
# Description: Executes a shell command if the user press yes.

# The command (first word) cannot have spaces.
# Good:
#   shutdown -h now
# Bad:
#   "~/my scripts/script to do something.sh" abc

STRING_SIZE_LIMIT=25
THEME=~/.config/rofi/prompt-theme.rasi

rofi_error() {
    rofi -e "rofi-prompt: Error: $1"
}

if [ $# -ne 2 ]; then
    rofi_error " You passed $# args. Usage: prompt.sh ACTION COMMAND"
    exit 1
fi

ACTION="$1"
COMMAND="$2"

if [ ${#ACTION} -gt $STRING_SIZE_LIMIT ]; then
    rofi_error "$ACTION too long, limit its size to $STRING_SIZE_LIMIT."
    exit 1
fi

ANSWER=$(
    echo -e "Yes\nNo"\ | rofi -dmenu -i -p "Are you sure about $ACTION?"\
                         -theme $THEME
)

command -v "${COMMAND%% *}" > /dev/null
if [ $? -ne 0 ]; then
    rofi_error "Command $COMMAND could not be found or could not be invoked."
    exit 1
fi

case "$ANSWER"
in
    Yes) $COMMAND ;;
    *) ;;
esac
