#!/usr/bin/env bash

# This script reads the regular file $FILE_PATH, which must contain, line by line,
# your frequently used texts. It can be a phone number, or an email that 
# you always forget (or a crazy password that you know that it's safe there 
# IN PLAIN TEXT). After reading the file, a menu will popup showing the texts
# that you can select to copy to the system's clipboard. 
# You can make inline comments in this file by using # at the end of line. 
#
# Example:
#
# $FILE_PATH content:
# 9999-9999 # boss phone
# 192.168.1.1 # my office pc static ip
# Logitech G502 # moush that i always forget the name

FILE_PATH="$HOME/.quick-clipboard.txt"
ROFI_THEME="$HOME/.include/rofi-themes/dmenu-center-search.rasi"

run() {
    if [ ! -f "$FILE_PATH" ]; then
        notify_error "File \"$FILE_PATH\" does not exists."
        exit 1
    fi

    SELECTED_OPTION="$(ask_user_to_select_option)"
    [[ -z "$SELECTED_OPTION" ]] && exit

    TO_COPY="$(remove_comment_and_trim "$SELECTED_OPTION")"

    copy_to_clipboard "$TO_COPY"
    # notify_result $?
}

notify() {
    notify-send "$1"
}

notify_error() {
    notify-send --urgency="critical" "$1"
}

ask_user_to_select_option() {
    cat "$FILE_PATH" | rofi -theme "$ROFI_THEME" -dmenu  -i -no-custom
}

remove_comment_and_trim() {
    STRING="$1"
    UNCOMMENTED_STRING="${STRING%#*}"
    FORMATTED_STRING="$(echo "$UNCOMMENTED_STRING" | sed 's/\s*$//g')"

    echo "$FORMATTED_STRING"
}

copy_to_clipboard() {
    STRING="$1"

    echo -n "$STRING" | xclip -sel clip
}

notify_result() {
    RETURN_VALUE=$1

    if [ $RETURN_VALUE -eq 0 ]; then
        notify "\"$TO_COPY\" copied to clipboard."
    else
        notify_error "xclip: Failed to copy to clipboard"
    fi
}

run
