#!/bin/bash

PACKAGE="org.flameshot.Flameshot"
FLAMESHOT="$(flatpak list | grep -e $PACKAGE)"

if [ -z "$FLAMESHOT" ]; then
    echo "Flameshot is not installed. Installing..."
    flatpak install $PACKAGE -y
    flatpak permission-set \
        screenshot \
        screenshot \
        $PACKAGE \
        yes
fi

flatpak run $PACKAGE gui -r | wl-copy
