#!/usr/bin/env bash
# Description: Uses ffmpeg to make a video sendable through whatsapp.

convert_video_to_mp4_whatsapp_compliant() {
    VIDEO_TO_CONVERT_PATH="$1"
    VIDEO_CONVERTED_PATH="$2"

    SCREEN_RESOLUTION="$(xdpyinfo | grep dimensions | awk '{print $2}')"

    ffmpeg \
        -thread_queue_size 512 \
        -i "$VIDEO_TO_CONVERT_PATH" \
        -probesize 10M \
        -y \
        -s "$SCREEN_RESOLUTION" \
        -r 60 \
        -c:v libx264 \
        -preset fast \
        -profile:v baseline \
        -level 3.0 \
        -pix_fmt yuv420p \
        "$VIDEO_CONVERTED_PATH"
}

if [ $# -ne 2 ]
then
    echo "Usage: zapfy input_video output_video"
    exit 1
fi

if [ ! -f "$1" ]
then
    echo "No such regular file: \"$1\""
    exit 1
fi

if [ -e "$2" ]
then
    echo "File \"$2\" already exists."
    exit 1
fi

convert_video_to_mp4_whatsapp_compliant "$1" "$2"
